//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match2DateAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakti
    {
        public string id { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string brojTelefona { get; set; }
        public byte[] version { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public System.DateTimeOffset updatedAt { get; set; }
        public bool deleted { get; set; }
    
        public virtual korisnici korisnici { get; set; }
    }
}
