//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match2DateAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public korisnici()
        {
            this.Kontaktis = new HashSet<Kontakti>();
        }
    
        public string id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string email { get; set; }
        public string sifra { get; set; }
        public string spol { get; set; }
        public string grad { get; set; }
        public string opis { get; set; }
        public Nullable<bool> aktivan { get; set; }
        public Nullable<System.DateTimeOffset> datumRodjenja { get; set; }
        public Nullable<double> ocjena { get; set; }
        public Nullable<bool> deleted { get; set; }
        public byte[] version { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public System.DateTimeOffset updatedAt { get; set; }
        public string slika1 { get; set; }
        public string slika2 { get; set; }
        public string slika3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontakti> Kontaktis { get; set; }
    }
}
